
version: '3.8'

services:
  # Frontend en mode développement
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.frontend.dev
    container_name: pulsar-frontend-dev
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:5002
    networks:
      - pulsar-network
    command: npm run dev -- --host 0.0.0.0

  # Backend en mode développement
  backend-dev:
    build:
      context: .
      dockerfile: Dockerfile.backend.dev
    container_name: pulsar-backend-dev
    ports:
      - "5002:5002"
    volumes:
      - ./backend:/app
      - backend_dev_data:/app/data
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=true
      - DATABASE_URL=sqlite:///data/irrigation_logs.db
      - MQTT_BROKER_HOST=217.182.210.54
      - MQTT_BROKER_PORT=1883
    networks:
      - pulsar-network
    command: python app.py

volumes:
  backend_dev_data:
    driver: local

networks:
  pulsar-network:
    driver: bridge
